server:
  port: 5155
  host: localhost
  nodeEnv: development

cors:
  origin: "true"
  credentials: true
  methods: "GET,POST,PUT,DELETE,OPTIONS"
  headers: "Origin,X-Requested-With,Content-Type,Accept,Authorization"

cache:
  directory: ".cache"
  httpHeader:
    maxAge: 2592000 # 30 days
    control: "public, immutable"
  storage:
    maxSize: null
    ttl: 2592000 # 30 days

image:
  processing:
    defaultQuality: 80
    defaultPngCompressionLevel: 6
    maxWidth: 3840
    maxHeight: 2160

repositories:
  example-repo:
    localPath: "example"
    description: "Example repository"
    images:
      png:
        storage:
          ttl: 2592000 # 30 days
    contents:
      ogg: {}

analytics:
  # Google Analytics configuration for API usage tracking
  # To obtain these values:
  # 1. measurementId: Go to Google Analytics > Admin > Data Streams > Select your stream > View measurement ID (format: G-XXXXXXXXXX)
  # 2. apiSecret: In the same Data Streams page > Measurement Protocol API secrets > Create new secret
  #    - Give it a nickname (e.g., "CDN Analytics")
  #    - Copy the generated secret value
  # Note: You need a Google Analytics 4 (GA4) property to use the Measurement Protocol
  measurementId: "G-XXXXXXXXXX"
  apiSecret: "your_api_secret_here"
  enabled: false
  endpoint: "https://www.google-analytics.com/mp/collect"
