stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - template: /.azure/templates/checkout.yml

          - template: /.azure/templates/setup.yml

          - script: yarn run tsc
            displayName: 'TS Typecheck'

          - script: yarn run lint
            displayName: 'Run ESLint'

          - script: yarn run test:ci
            displayName: 'Test Source'

          - script: yarn run build
            displayName: 'Build'

          - pwsh: Remove-Item -Recurse -Force node_modules
            displayName: 'Remove Node Modules'

          - pwsh: Remove-Item -Recurse -Force src
            displayName: 'Remove Source Files'

          - task: ArchiveFiles@2
            displayName: 'Archive Build'
            inputs:
              rootFolderOrFile: .
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).zip'
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).zip'
              artifactName: '$(APP_FOLDER_NAME)-artifact'
              publishLocation: 'Container'
