trigger:
  branches:
    include:
      - main

variables:
  - template: /.azure/variables/node.yml
  - template: /.azure/variables/repo.yml
  - template: /.azure/variables/yarn.yml

pool:
  vmImage: windows-latest

stages:
  - template: /.azure/templates/run.yml
